// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Listing struct {
	ID        int64
	Address   string
	FloorArea pgtype.Numeric
	Price     int64
}
