// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: listing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ExternalId    string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	FloorArea     float64                `protobuf:"fixed64,5,opt,name=floor_area,json=floorArea,proto3" json:"floor_area,omitempty"`
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	Occupied      bool                   `protobuf:"varint,7,opt,name=occupied,proto3" json:"occupied,omitempty"`
	ImageLoaded   bool                   `protobuf:"varint,8,opt,name=image_loaded,json=imageLoaded,proto3" json:"image_loaded,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,9,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Listing) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Listing) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Listing) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Listing) GetFloorArea() float64 {
	if x != nil {
		return x.FloorArea
	}
	return 0
}

func (x *Listing) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetOccupied() bool {
	if x != nil {
		return x.Occupied
	}
	return false
}

func (x *Listing) GetImageLoaded() bool {
	if x != nil {
		return x.ImageLoaded
	}
	return false
}

func (x *Listing) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type GetListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsRequest) Reset() {
	*x = GetListingsRequest{}
	mi := &file_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsRequest) ProtoMessage() {}

func (x *GetListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsRequest.ProtoReflect.Descriptor instead.
func (*GetListingsRequest) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{1}
}

type GetListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsResponse) Reset() {
	*x = GetListingsResponse{}
	mi := &file_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsResponse) ProtoMessage() {}

func (x *GetListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsResponse.ProtoReflect.Descriptor instead.
func (*GetListingsResponse) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{2}
}

func (x *GetListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

var File_listing_proto protoreflect.FileDescriptor

const file_listing_proto_rawDesc = "" +
	"\n" +
	"\rlisting.proto\x12\thomagochi\"\xff\x01\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"floor_area\x18\x05 \x01(\x01R\tfloorArea\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x1a\n" +
	"\boccupied\x18\a \x01(\bR\boccupied\x12!\n" +
	"\fimage_loaded\x18\b \x01(\bR\vimageLoaded\x12\x1d\n" +
	"\n" +
	"image_urls\x18\t \x03(\tR\timageUrls\"\x14\n" +
	"\x12GetListingsRequest\"E\n" +
	"\x13GetListingsResponse\x12.\n" +
	"\blistings\x18\x01 \x03(\v2\x12.homagochi.ListingR\blistings2^\n" +
	"\x0eListingService\x12L\n" +
	"\vGetListings\x12\x1d.homagochi.GetListingsRequest\x1a\x1e.homagochi.GetListingsResponseB9Z7gitlab.com/shanemaglangit/homagochi/backend/internal/pbb\x06proto3"

var (
	file_listing_proto_rawDescOnce sync.Once
	file_listing_proto_rawDescData []byte
)

func file_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)))
	})
	return file_listing_proto_rawDescData
}

var file_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_listing_proto_goTypes = []any{
	(*Listing)(nil),             // 0: homagochi.Listing
	(*GetListingsRequest)(nil),  // 1: homagochi.GetListingsRequest
	(*GetListingsResponse)(nil), // 2: homagochi.GetListingsResponse
}
var file_listing_proto_depIdxs = []int32{
	0, // 0: homagochi.GetListingsResponse.listings:type_name -> homagochi.Listing
	1, // 1: homagochi.ListingService.GetListings:input_type -> homagochi.GetListingsRequest
	2, // 2: homagochi.ListingService.GetListings:output_type -> homagochi.GetListingsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_listing_proto_init() }
func file_listing_proto_init() {
	if File_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_depIdxs,
		MessageInfos:      file_listing_proto_msgTypes,
	}.Build()
	File_listing_proto = out.File
	file_listing_proto_goTypes = nil
	file_listing_proto_depIdxs = nil
}
