// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Listing struct {
	ID        int64           `json:"id"`
	Address   string          `json:"address"`
	Price     int64           `json:"price"`
	FloorArea float64         `json:"floorArea"`
	LotArea   float64         `json:"lotArea"`
	Latitude  float64         `json:"latitude"`
	Longitude float64         `json:"longitude"`
	Images    []*ListingImage `json:"images"`
}

type ListingConnection struct {
	Edges []*ListingEdge `json:"edges"`
	Nodes []*Listing     `json:"nodes"`
}

type ListingEdge struct {
	Node   *Listing `json:"node"`
	Cursor string   `json:"cursor"`
}

type ListingImage struct {
	ID        int64  `json:"id"`
	ListingID int64  `json:"listingId"`
	URL       string `json:"url"`
}

type Query struct {
}
