// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: listing_service.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsRequest) Reset() {
	*x = GetListingsRequest{}
	mi := &file_listing_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsRequest) ProtoMessage() {}

func (x *GetListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsRequest.ProtoReflect.Descriptor instead.
func (*GetListingsRequest) Descriptor() ([]byte, []int) {
	return file_listing_service_proto_rawDescGZIP(), []int{0}
}

type GetListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsResponse) Reset() {
	*x = GetListingsResponse{}
	mi := &file_listing_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsResponse) ProtoMessage() {}

func (x *GetListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsResponse.ProtoReflect.Descriptor instead.
func (*GetListingsResponse) Descriptor() ([]byte, []int) {
	return file_listing_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

var File_listing_service_proto protoreflect.FileDescriptor

const file_listing_service_proto_rawDesc = "" +
	"\n" +
	"\x15listing_service.proto\x12\alisting\x1a\rlisting.proto\"\x14\n" +
	"\x12GetListingsRequest\"C\n" +
	"\x13GetListingsResponse\x12,\n" +
	"\blistings\x18\x01 \x03(\v2\x10.listing.ListingR\blistings2Z\n" +
	"\x0eListingService\x12H\n" +
	"\vGetListings\x12\x1b.listing.GetListingsRequest\x1a\x1c.listing.GetListingsResponseB?Z=gitlab.com/shanemaglangit/homagochi/backend/internal/protobufb\x06proto3"

var (
	file_listing_service_proto_rawDescOnce sync.Once
	file_listing_service_proto_rawDescData []byte
)

func file_listing_service_proto_rawDescGZIP() []byte {
	file_listing_service_proto_rawDescOnce.Do(func() {
		file_listing_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_service_proto_rawDesc), len(file_listing_service_proto_rawDesc)))
	})
	return file_listing_service_proto_rawDescData
}

var file_listing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_listing_service_proto_goTypes = []any{
	(*GetListingsRequest)(nil),  // 0: listing.GetListingsRequest
	(*GetListingsResponse)(nil), // 1: listing.GetListingsResponse
	(*Listing)(nil),             // 2: listing.Listing
}
var file_listing_service_proto_depIdxs = []int32{
	2, // 0: listing.GetListingsResponse.listings:type_name -> listing.Listing
	0, // 1: listing.ListingService.GetListings:input_type -> listing.GetListingsRequest
	1, // 2: listing.ListingService.GetListings:output_type -> listing.GetListingsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_listing_service_proto_init() }
func file_listing_service_proto_init() {
	if File_listing_service_proto != nil {
		return
	}
	file_listing_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_service_proto_rawDesc), len(file_listing_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listing_service_proto_goTypes,
		DependencyIndexes: file_listing_service_proto_depIdxs,
		MessageInfos:      file_listing_service_proto_msgTypes,
	}.Build()
	File_listing_service_proto = out.File
	file_listing_service_proto_goTypes = nil
	file_listing_service_proto_depIdxs = nil
}
