// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: listing.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listing struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ExternalId      string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Address         string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	FloorArea       float64                `protobuf:"fixed64,5,opt,name=floor_area,json=floorArea,proto3" json:"floor_area,omitempty"`
	Price           int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	OccupancyStatus string                 `protobuf:"bytes,7,opt,name=occupancy_status,json=occupancyStatus,proto3" json:"occupancy_status,omitempty"`
	ImageUrls       []string               `protobuf:"bytes,8,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	Payload         string                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Listing) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Listing) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Listing) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Listing) GetFloorArea() float64 {
	if x != nil {
		return x.FloorArea
	}
	return 0
}

func (x *Listing) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Listing) GetOccupancyStatus() string {
	if x != nil {
		return x.OccupancyStatus
	}
	return ""
}

func (x *Listing) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Listing) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_listing_proto protoreflect.FileDescriptor

const file_listing_proto_rawDesc = "" +
	"\n" +
	"\rlisting.proto\x12\alisting\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x02\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"floor_area\x18\x05 \x01(\x01R\tfloorArea\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12)\n" +
	"\x10occupancy_status\x18\a \x01(\tR\x0foccupancyStatus\x12\x1d\n" +
	"\n" +
	"image_urls\x18\b \x03(\tR\timageUrls\x12\x18\n" +
	"\apayload\x18\t \x01(\tR\apayloadB?Z=gitlab.com/shanemaglangit/homagochi/backend/internal/protobufb\x06proto3"

var (
	file_listing_proto_rawDescOnce sync.Once
	file_listing_proto_rawDescData []byte
)

func file_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)))
	})
	return file_listing_proto_rawDescData
}

var file_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_listing_proto_goTypes = []any{
	(*Listing)(nil), // 0: listing.Listing
}
var file_listing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_listing_proto_init() }
func file_listing_proto_init() {
	if File_listing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_depIdxs,
		MessageInfos:      file_listing_proto_msgTypes,
	}.Build()
	File_listing_proto = out.File
	file_listing_proto_goTypes = nil
	file_listing_proto_depIdxs = nil
}
