// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: listing_service.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListingsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	After             *int64                 `protobuf:"varint,1,opt,name=after,proto3,oneof" json:"after,omitempty"`
	Before            *int64                 `protobuf:"varint,2,opt,name=before,proto3,oneof" json:"before,omitempty"`
	Limit             int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Search            string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	Sources           []string               `protobuf:"bytes,5,rep,name=sources,proto3" json:"sources,omitempty"`
	OccupancyStatuses []string               `protobuf:"bytes,6,rep,name=occupancy_statuses,json=occupancyStatuses,proto3" json:"occupancy_statuses,omitempty"`
	MinPrice          int64                  `protobuf:"varint,7,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice          *int64                 `protobuf:"varint,8,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetListingsRequest) Reset() {
	*x = GetListingsRequest{}
	mi := &file_listing_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsRequest) ProtoMessage() {}

func (x *GetListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listing_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsRequest.ProtoReflect.Descriptor instead.
func (*GetListingsRequest) Descriptor() ([]byte, []int) {
	return file_listing_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetListingsRequest) GetAfter() int64 {
	if x != nil && x.After != nil {
		return *x.After
	}
	return 0
}

func (x *GetListingsRequest) GetBefore() int64 {
	if x != nil && x.Before != nil {
		return *x.Before
	}
	return 0
}

func (x *GetListingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListingsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetListingsRequest) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GetListingsRequest) GetOccupancyStatuses() []string {
	if x != nil {
		return x.OccupancyStatuses
	}
	return nil
}

func (x *GetListingsRequest) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GetListingsRequest) GetMaxPrice() int64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

type GetListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsResponse) Reset() {
	*x = GetListingsResponse{}
	mi := &file_listing_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsResponse) ProtoMessage() {}

func (x *GetListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listing_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsResponse.ProtoReflect.Descriptor instead.
func (*GetListingsResponse) Descriptor() ([]byte, []int) {
	return file_listing_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *GetListingsResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_listing_service_proto protoreflect.FileDescriptor

const file_listing_service_proto_rawDesc = "" +
	"\n" +
	"\x15listing_service.proto\x12\alisting\x1a\fcommon.proto\x1a\rlisting.proto\"\xa5\x02\n" +
	"\x12GetListingsRequest\x12\x19\n" +
	"\x05after\x18\x01 \x01(\x03H\x00R\x05after\x88\x01\x01\x12\x1b\n" +
	"\x06before\x18\x02 \x01(\x03H\x01R\x06before\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12\x18\n" +
	"\asources\x18\x05 \x03(\tR\asources\x12-\n" +
	"\x12occupancy_statuses\x18\x06 \x03(\tR\x11occupancyStatuses\x12\x1b\n" +
	"\tmin_price\x18\a \x01(\x03R\bminPrice\x12 \n" +
	"\tmax_price\x18\b \x01(\x03H\x02R\bmaxPrice\x88\x01\x01B\b\n" +
	"\x06_afterB\t\n" +
	"\a_beforeB\f\n" +
	"\n" +
	"_max_price\"q\n" +
	"\x13GetListingsResponse\x12,\n" +
	"\blistings\x18\x01 \x03(\v2\x10.listing.ListingR\blistings\x12,\n" +
	"\bpageInfo\x18\x02 \x01(\v2\x10.common.PageInfoR\bpageInfo2Z\n" +
	"\x0eListingService\x12H\n" +
	"\vGetListings\x12\x1b.listing.GetListingsRequest\x1a\x1c.listing.GetListingsResponseB?Z=gitlab.com/shanemaglangit/homagochi/backend/internal/protobufb\x06proto3"

var (
	file_listing_service_proto_rawDescOnce sync.Once
	file_listing_service_proto_rawDescData []byte
)

func file_listing_service_proto_rawDescGZIP() []byte {
	file_listing_service_proto_rawDescOnce.Do(func() {
		file_listing_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_service_proto_rawDesc), len(file_listing_service_proto_rawDesc)))
	})
	return file_listing_service_proto_rawDescData
}

var file_listing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_listing_service_proto_goTypes = []any{
	(*GetListingsRequest)(nil),  // 0: listing.GetListingsRequest
	(*GetListingsResponse)(nil), // 1: listing.GetListingsResponse
	(*Listing)(nil),             // 2: listing.Listing
	(*PageInfo)(nil),            // 3: common.PageInfo
}
var file_listing_service_proto_depIdxs = []int32{
	2, // 0: listing.GetListingsResponse.listings:type_name -> listing.Listing
	3, // 1: listing.GetListingsResponse.pageInfo:type_name -> common.PageInfo
	0, // 2: listing.ListingService.GetListings:input_type -> listing.GetListingsRequest
	1, // 3: listing.ListingService.GetListings:output_type -> listing.GetListingsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_listing_service_proto_init() }
func file_listing_service_proto_init() {
	if File_listing_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_listing_proto_init()
	file_listing_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_service_proto_rawDesc), len(file_listing_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listing_service_proto_goTypes,
		DependencyIndexes: file_listing_service_proto_depIdxs,
		MessageInfos:      file_listing_service_proto_msgTypes,
	}.Build()
	File_listing_service_proto = out.File
	file_listing_service_proto_goTypes = nil
	file_listing_service_proto_depIdxs = nil
}
