import type {Metadata} from "next";
import "./global.css";
import {ReactNode} from "react";
import {Inter} from 'next/font/google'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" className={inter.className}>
            <body className="container mx-auto">
            {children}
            </body>
        </html>
    );
}
