// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: listings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getListing = `-- name: GetListing :one
SELECT id, source, external_id, address, floor_area, lot_area, price, image_loaded, occupancy_status, created_at, updated_at, payload, status, geocoded_at, coordinate
FROM listings
WHERE id = $1::bigint
LIMIT 1
`

func (q *Queries) GetListing(ctx context.Context, id int64) (*Listing, error) {
	row := q.db.QueryRow(ctx, getListing, id)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Address,
		&i.FloorArea,
		&i.LotArea,
		&i.Price,
		&i.ImageLoaded,
		&i.OccupancyStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Payload,
		&i.Status,
		&i.GeocodedAt,
		&i.Coordinate,
	)
	return &i, err
}

const getListingByImageNotLoaded = `-- name: GetListingByImageNotLoaded :one
SELECT id, external_id, payload
FROM listings
WHERE source = $1::source
  AND image_loaded = FALSE
LIMIT 1
`

type GetListingByImageNotLoadedRow struct {
	ID         int64
	ExternalID string
	Payload    []byte
}

func (q *Queries) GetListingByImageNotLoaded(ctx context.Context, source Source) (*GetListingByImageNotLoadedRow, error) {
	row := q.db.QueryRow(ctx, getListingByImageNotLoaded, source)
	var i GetListingByImageNotLoadedRow
	err := row.Scan(&i.ID, &i.ExternalID, &i.Payload)
	return &i, err
}

const getListingNotGeocoded = `-- name: GetListingNotGeocoded :one
SELECT id, address
FROM listings
WHERE geocoded_at IS NULL
  AND status = 'active'::listing_status
LIMIT 1
`

type GetListingNotGeocodedRow struct {
	ID      int64
	Address string
}

func (q *Queries) GetListingNotGeocoded(ctx context.Context) (*GetListingNotGeocodedRow, error) {
	row := q.db.QueryRow(ctx, getListingNotGeocoded)
	var i GetListingNotGeocodedRow
	err := row.Scan(&i.ID, &i.Address)
	return &i, err
}

const getListingsInBoundary = `-- name: GetListingsInBoundary :many
SELECT id, source, external_id, address, floor_area, lot_area, price, image_loaded, occupancy_status, created_at, updated_at, payload, status, geocoded_at, coordinate
FROM listings
WHERE ST_Intersects(
        coordinate,
        ST_SetSRID(ST_MakeEnvelope($1::double precision, $2::double precision, $3::double precision, $4::double precision), 4326)::geography
      )
  AND address ILIKE '%' || $5::text || '%'
  AND source = ANY ($6::source[])
  AND occupancy_status = ANY ($7::occupancy_status[])
  AND price BETWEEN $8::bigint AND COALESCE($9, 9223372036854775807)
  AND status = 'active'
  AND geocoded_at IS NOT NULL
LIMIT 1000
`

type GetListingsInBoundaryParams struct {
	MinLng            float64
	MinLat            float64
	MaxLng            float64
	MaxLat            float64
	Address           string
	Sources           []Source
	OccupancyStatuses []OccupancyStatus
	MinPrice          int64
	MaxPrice          pgtype.Int8
}

func (q *Queries) GetListingsInBoundary(ctx context.Context, arg GetListingsInBoundaryParams) ([]*Listing, error) {
	rows, err := q.db.Query(ctx, getListingsInBoundary,
		arg.MinLng,
		arg.MinLat,
		arg.MaxLng,
		arg.MaxLat,
		arg.Address,
		arg.Sources,
		arg.OccupancyStatuses,
		arg.MinPrice,
		arg.MaxPrice,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Address,
			&i.FloorArea,
			&i.LotArea,
			&i.Price,
			&i.ImageLoaded,
			&i.OccupancyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Payload,
			&i.Status,
			&i.GeocodedAt,
			&i.Coordinate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListingsNextPage = `-- name: GetListingsNextPage :many
SELECT id, source, external_id, address, floor_area, lot_area, price, image_loaded, occupancy_status, created_at, updated_at, payload, status, geocoded_at, coordinate
FROM listings
WHERE id > $1::bigint
  AND address ILIKE '%' || $2::text || '%'
  AND source = ANY ($3::source[])
  AND occupancy_status = ANY ($4::occupancy_status[])
  AND price BETWEEN $5::bigint AND COALESCE($6, 9223372036854775807)
  AND status = 'active'
  AND geocoded_at IS NOT NULL
ORDER BY id
LIMIT $7::int
`

type GetListingsNextPageParams struct {
	After             int64
	Address           string
	Sources           []Source
	OccupancyStatuses []OccupancyStatus
	MinPrice          int64
	MaxPrice          pgtype.Int8
	RowLimit          int32
}

func (q *Queries) GetListingsNextPage(ctx context.Context, arg GetListingsNextPageParams) ([]*Listing, error) {
	rows, err := q.db.Query(ctx, getListingsNextPage,
		arg.After,
		arg.Address,
		arg.Sources,
		arg.OccupancyStatuses,
		arg.MinPrice,
		arg.MaxPrice,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Address,
			&i.FloorArea,
			&i.LotArea,
			&i.Price,
			&i.ImageLoaded,
			&i.OccupancyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Payload,
			&i.Status,
			&i.GeocodedAt,
			&i.Coordinate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListingsPrevPage = `-- name: GetListingsPrevPage :many
SELECT id, source, external_id, address, floor_area, lot_area, price, image_loaded, occupancy_status, created_at, updated_at, payload, status, geocoded_at, coordinate
FROM listings
WHERE id < $1::bigint
  AND address ILIKE '%' || $2::text || '%'
  AND source = ANY ($3::source[])
  AND occupancy_status = ANY ($4::occupancy_status[])
  AND price BETWEEN $5::bigint AND COALESCE($6, 9223372036854775807)
  AND status = 'active'
  AND geocoded_at IS NOT NULL
ORDER BY id DESC
LIMIT $7::int
`

type GetListingsPrevPageParams struct {
	Before            int64
	Address           string
	Sources           []Source
	OccupancyStatuses []OccupancyStatus
	MinPrice          int64
	MaxPrice          pgtype.Int8
	RowLimit          int32
}

func (q *Queries) GetListingsPrevPage(ctx context.Context, arg GetListingsPrevPageParams) ([]*Listing, error) {
	rows, err := q.db.Query(ctx, getListingsPrevPage,
		arg.Before,
		arg.Address,
		arg.Sources,
		arg.OccupancyStatuses,
		arg.MinPrice,
		arg.MaxPrice,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Address,
			&i.FloorArea,
			&i.LotArea,
			&i.Price,
			&i.ImageLoaded,
			&i.OccupancyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Payload,
			&i.Status,
			&i.GeocodedAt,
			&i.Coordinate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertListings = `-- name: InsertListings :exec
INSERT INTO listings (external_id, source, address, floor_area, lot_area, price, occupancy_status, payload)
VALUES (unnest($1::text[]),
        unnest($2::source[]),
        unnest($3::text[]),
        unnest($4::numeric(8, 2)[]),
        unnest($5::numeric(8, 2)[]),
        unnest($6::bigint[]),
        unnest($7::occupancy_status[]),
        unnest($8::jsonb[]))
ON CONFLICT (source, external_id) DO UPDATE
    SET address          = EXCLUDED.address,
        floor_area       = EXCLUDED.floor_area,
        lot_area         = EXCLUDED.lot_area,
        price            = EXCLUDED.price,
        occupancy_status = EXCLUDED.occupancy_status,
        payload          = EXCLUDED.payload,
        status           = 'active'::listing_status,
        updated_at       = NOW()
`

type InsertListingsParams struct {
	ExternalIds       []string
	Sources           []Source
	Addresses         []string
	FloorAreas        []pgtype.Numeric
	LotAreas          []pgtype.Numeric
	Prices            []int64
	OccupancyStatuses []OccupancyStatus
	Payloads          [][]byte
}

func (q *Queries) InsertListings(ctx context.Context, arg InsertListingsParams) error {
	_, err := q.db.Exec(ctx, insertListings,
		arg.ExternalIds,
		arg.Sources,
		arg.Addresses,
		arg.FloorAreas,
		arg.LotAreas,
		arg.Prices,
		arg.OccupancyStatuses,
		arg.Payloads,
	)
	return err
}

const unlistOldListings = `-- name: UnlistOldListings :exec
UPDATE listings
SET status = 'unlisted'::listing_status
WHERE listings.source = $1::source
  AND listings.updated_at::date < CURRENT_DATE
`

func (q *Queries) UnlistOldListings(ctx context.Context, source Source) error {
	_, err := q.db.Exec(ctx, unlistOldListings, source)
	return err
}

const updateListingCoordinate = `-- name: UpdateListingCoordinate :exec
UPDATE listings
SET coordinate  = ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography,
    geocoded_at = NOW()
WHERE id = $3::bigint
`

type UpdateListingCoordinateParams struct {
	Lng float64
	Lat float64
	ID  int64
}

func (q *Queries) UpdateListingCoordinate(ctx context.Context, arg UpdateListingCoordinateParams) error {
	_, err := q.db.Exec(ctx, updateListingCoordinate, arg.Lng, arg.Lat, arg.ID)
	return err
}

const updateListingsImageLoaded = `-- name: UpdateListingsImageLoaded :exec
UPDATE listings
SET image_loaded = $1::boolean
WHERE listings.id = $2::bigint
`

type UpdateListingsImageLoadedParams struct {
	ImageLoaded bool
	ID          int64
}

func (q *Queries) UpdateListingsImageLoaded(ctx context.Context, arg UpdateListingsImageLoadedParams) error {
	_, err := q.db.Exec(ctx, updateListingsImageLoaded, arg.ImageLoaded, arg.ID)
	return err
}
