// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"
)

const getListings = `-- name: GetListings :many
SELECT id, source, external_id, address, floor_area, price, image_loaded, occupancy_status, created_at, updated_at, payload, status, geocoded_at, coordinate
FROM listings
LIMIT 20
`

func (q *Queries) GetListings(ctx context.Context) ([]*Listing, error) {
	rows, err := q.db.Query(ctx, getListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Address,
			&i.FloorArea,
			&i.Price,
			&i.ImageLoaded,
			&i.OccupancyStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Payload,
			&i.Status,
			&i.GeocodedAt,
			&i.Coordinate,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
