// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Listing struct {
	ID         int64
	ExternalID string
	Address    string
	FloorArea  pgtype.Numeric
	Price      int64
	Occupied   bool
}
