// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getListings = `-- name: GetListings :many
SELECT id, source, external_id, address, floor_area, price, occupied
FROM listings
LIMIT $1::int
`

func (q *Queries) GetListings(ctx context.Context, rowLimit int32) ([]*Listing, error) {
	rows, err := q.db.Query(ctx, getListings, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Listing
	for rows.Next() {
		var i Listing
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Address,
			&i.FloorArea,
			&i.Price,
			&i.Occupied,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertListings = `-- name: InsertListings :exec
INSERT INTO listings (source, external_id, address, floor_area, price, occupied)
VALUES (unnest($1::source[]),
        unnest($2::text[]),
        unnest($3::text[]),
        unnest($4::numeric(8, 2)[]),
        unnest($5::bigint[]),
        unnest($6::boolean[]))
ON CONFLICT (source, external_id) DO UPDATE
    SET address    = EXCLUDED.address,
        floor_area = EXCLUDED.floor_area,
        price      = EXCLUDED.price,
        occupied   = EXCLUDED.occupied
`

type InsertListingsParams struct {
	Sources     []Source
	ExternalIds []string
	Addresses   []string
	FloorAreas  []pgtype.Numeric
	Prices      []int64
	Occupied    []bool
}

func (q *Queries) InsertListings(ctx context.Context, arg InsertListingsParams) error {
	_, err := q.db.Exec(ctx, insertListings,
		arg.Sources,
		arg.ExternalIds,
		arg.Addresses,
		arg.FloorAreas,
		arg.Prices,
		arg.Occupied,
	)
	return err
}
