include:
  - component: gitlab.com/components/opentofu/validate-plan-apply@2.0.0-rc1
    inputs:
      version: 2.0.0-rc1
      opentofu_version: 1.9.0
      root_dir: terraform/
      state_name: production